#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# CREATE A MYSQL DATABASE
#=================================================
ynh_script_progression "Configuring a MySQL database..."

ynh_psql_db_shell  <<< "ALTER DATABASE $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD NODE DEPENDENCIES
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
    #ynh_hide_warnings yarn install
    #ynh_hide_warnings yarn build:frontend:app
    #ynh_hide_warnings yarn build:server
    ynh_hide_warnings ynh_exec_as_app npm install --prefix "$install_dir" -g facilmap-client@"$(ynh_app_upstream_version)"
    ynh_hide_warnings ynh_exec_as_app npm install --prefix "$install_dir" -g facilmap-server@"$(ynh_app_upstream_version)"
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding configuration..."

ynh_config_add --template="config.env" --destination="$install_dir/config.env"

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Collaborative maps and routing" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Server started"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
