#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading NodeJS..."

ynh_nodejs_install

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# BUILD NODE DEPENDENCIES
#=================================================
ynh_script_progression "Install $app..."

pushd "$install_dir"
    ynh_hide_warnings env node_load_PATH yarn install
    ynh_hide_warnings env node_load_PATH yarn build:frontend:app
    ynh_hide_warnings env node_load_PATH yarn build:server
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating config files..."

ynh_config_add --template="config.env" --destination="$install_dir/config.env"

chown -R "$app:www-data" "$install_dir/config.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Collaborative maps and routing" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Server started"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
